# java-db service
apiVersion: v1
kind: Service
metadata:
  name: java-db
spec:
  selector:
    app: java-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
# java-app service
apiVersion: v1
kind: Service
metadata:
  name: java-app
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# java-db deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-db
  template:
    metadata:
      labels:
        app: java-db
    spec:
      containers:
        - name: postgres
          image: postgres:12
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
          ports:
            - containerPort: 5432
              name: postgres
---
# java-app deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
          - name: java-app
            image: jayanth999/java_app:1.0.0
            ports:
              - containerPort: 8080
            env:
              - name: DATABASE_URL
                value: "jdbc:postgresql://java-db:5432/postgres"
              - name: DATABASE_USERNAME
                value: "postgres"
              - name: DATABASE_PASSWORD
                value: "postgres"
      depends_on:
        - java-db