apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-db
  template:
    metadata:
      labels:
        app: java-db
    spec:
      containers:
      - name: java-db
        image: postgres:12
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        emptyDir: {}